### ISSUE TITLE
Create JS file to populate HTML

### ISSUE THREAD

**Issue by mariaciceri** [JedDizon/hackathon-dec-2025-team-7#15]
As a *developer* I need to *populate the HTML file according to the category in the JSON file*

## Acceptance Criteria

- The file reads and parses the data from the JSON file to the JS file
- The data is available to be used as a JS object
- The code populates the HTML file according to the category of the surprise of the day

## Tasks
- [x]  Fetch the data stored in the JSON file
- [x] Parse it into an object in the JS file
- [x] Add category verification for each key-value pair
- [x] Write the appropriate code that will populate the HTML file every time the user clicks on a day on the calendar
- [x] Make sure the HTML file gets "cleaned up" before each new populating
