### ISSUE TITLE
Create calendar page

### ISSUE THREAD

**Issue by mariaciceri** [JedDizon/hackathon-dec-2025-team-7#16]
As a *user* I want *to be able to click on the different days of the month and see what the surprise is*.

## Acceptance Criteria
-  user can see the days of the month
- user can click on the day
- user can see what is "behind" the day

## Tasks

- [x] Have a background image with the days of the month displayed over it with a clear border
- [x] Days are clickable
- [x] When a day is clicked, it must only open if it is the right day or if it has passed
- [x] After opening, the "box" stays open, displaying a preview of the surprise.
- [x] The user can click again on the box to review the surprise.
