### ISSUE TITLE
create css

### ISSUE THREAD

**Issue by JedDizon** [JedDizon/hackathon-dec-2025-team-7#4]
As a *user* I want to *see a nice background and which doors I can open* 

## Acceptance Criteria

- Indication for doors that can be opened
- Indication for doors that can't be opened
- Something different for the doors I have already opened

## Tasks

- [x] Create/upload a background
- [x] Add something to indicate a door can be opened
- [ ] Add a nice transition to open door (optional)
- [x] Add indications when a door is disabled
- [x] Add style to opened door

**Comment by codemasterdevan** [comment]
I can handle all The Styling, unless you need me to work on something else?

**Comment by mariaciceri** [comment]
of course.. I have created a separated styling sheet for the home and door pages, just check in components for the className
